name: Release

on:
  push:
    tags:
      - v[0-9]+.*

jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/create-gh-release-action@v1
        # with:
        #   # (optional)
        #   changelog: CHANGELOG.md
        env:
          # (required)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-20.04
            build_tool: cross
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
            build_tool: cargo
          - target: x86_64-apple-darwin
            os: macos-latest
            build_tool: cargo
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            build_tool: cargo
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        name: Install cross-compilation tools
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: rust_hello_world
          # (optional) Target triple, default is host triple.
          target: ${{ matrix.target }}
          # (optional) Tool to build binaries (cargo, or cross)
          build_tool: ${{ matrix.build_tool }}
        env:
          # (required) GitHub token for uploading assets to GitHub Releases.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
